version: '2'
services:
    eafuse-app:
        image: eafuse
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://eafuse-mysql:3306/eafuse?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eafuse-mysql:
        extends:
            file: mysql.yml
            service: eafuse-mysql
